### ISSUE TITLE
在测试cls的推理代码出现问题

### ISSUE THREAD

**Issue by BandyKenny** [taifyang/yolov5-cls-det-seg-opencv#3]
后处理部分开始报错：
//后处理
string Yolo_cls::cls_post_process(std::vector<cv::Mat>& detections)
std::vector<float> values;
	for (size_t i = 0; i < detections[0].cols; i++)
	{
		values.push_back(detections[0].at<float>(0, i));
	}
	int id = std::distance(values.begin(), std::max_element(values.begin(), values.end()));
传进来的detections
![image](https://user-images.githubusercontent.com/43592362/228765266-05c3db3d-0f8e-4db9-af3c-2051673062ed.png)
debug发现：
![image](https://user-images.githubusercontent.com/43592362/228765549-b3e2813c-df09-4007-936f-fe5321371737.png)
循环这里取到的结果为-1，values.push_back()执行不下去，这个能怎样解决呀？

**Comment by BandyKenny** [comment]
或者说如果不是训练的1000类的模型，而是自己训练的二分类模型，那又该怎么改动使得可以到推理结果那里显示正常？

**Comment by BandyKenny** [comment]
就是无论怎么推理，在二分类上它总是在0维度为正值
![Uploading image.png…]()

**Comment by taifyang** [comment]
我觉得可能是onnx模型的问题

**Comment by taifyang** [comment]
你可以用netron查看一下onnx的output维度是多少。我怀疑是onnx文件问题或者OpenCV版本问题。

**Comment by BandyKenny** [comment]
![image](https://user-images.githubusercontent.com/43592362/228857495-e2c3a553-e66e-46a3-b6f2-9c319974cb76.png)
gan感觉output是对的，opencv和python的保持一致，都是4.5.4的

**Comment by BandyKenny** [comment]
嗯嗯，是的，我把onnx和测试图像都发你邮箱试试，谢谢啦

**Comment by taifyang** [comment]
我好像找到原因了，可能是前处理问题。看augmentations.py的第347行classify_transforms，除了归一化ToTensor操作还做了Normalize操作，但是似乎这个操作OpenCV算子不能完全对应，只能减去均值没有办法除以标准差。

**Comment by taifyang** [comment]
后处理就一个softmax操作，出问题可能性应该不大

**Comment by taifyang** [comment]
这个可以自己手动实现的，我简单实现了一下cpp和py对了一下网络推理输出tensor值差异不大。后续有空更新，你也可以看看有没有什么好的实现方法。

**Comment by BandyKenny** [comment]
额，我也不知道是不是我加的问题，但是对于结果来说，还是没解决问题😂
![image](https://user-images.githubusercontent.com/43592362/229339643-c92e8da5-9fef-4d0e-a32b-d44b768b5c65.png)

**Comment by taifyang** [comment]
倒数第二行的1/255应该是1，你前面已经乘过1/255了。我对比python和c++输出tensor结果基本是一致的。另外，长方形图片的话源代码还做了一个CenterCrop操作，可以去看一下，不加的话对推理精度可能有影响。

**Comment by BandyKenny** [comment]
suo噶，感谢指导😂

**Comment by BandyKenny** [comment]
![image](https://user-images.githubusercontent.com/43592362/229355167-ec23b935-a6be-4132-9454-3001b7127628.png)
按照博主的指导，基本上和python的推理效果一致了，🙇‍~~~///(^v^)\\\~~~

**Comment by taifyang** [comment]
好的，共同进步
